version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: documind-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: documind_password
      POSTGRES_DB: documind_db
    ports:
      - "5435:5432"
    volumes:
      - documind_data:/var/lib/postgresql/data

volumes:
  documind_data: